#!/usr/bin/env perl
use strict;
use warnings;
use Spellunker::CLI::Perl;
Spellunker::CLI::Perl->new->run();

__END__

=head1 NAME

spellunker-perl - Spelling checker

=head1 SYNOPSIS

    % spellunker-perl path/to/file
    % spellunker-perl < path/to/file

=head1 DESCRIPTION

This is yet another spelling checker.

You can check the spelling misses in your perl script.

